### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by 0marcey0** [voidpet/bugs#254] opened 2022-04-05 19:22 UTC
Shows an impossible state

I tried to go to the next area and this bug appeared

I thought it would just take me to the next area

![4DC20370-5EB6-42F1-8F2A-117513870357](https://user-images.githubusercontent.com/103070402/161833000-31c074a4-5e4b-4581-ae38-1971f89ebd1d.png)

 - Device: IPhone 7
 - OS: iOS 15.3.1
 - Browser: Default browser

**Comment by squidee100** [comment] 2022-04-05 21:45
Duplicate of #187

**Closed** 2022-04-06 17:42 UTC
