### ISSUE TITLE
Impossible State

### ISSUE THREAD

**Issue by Ditzgal** [voidpet/bugs#263] opened 2022-04-05 21:21 UTC
**Describe the bug**
Screen during exploration went to a blank screen with text.

**To Reproduce**
1. Go to 'explore’2. Go left of the voidpet with coffee 3. Go up

**Expected behavior**
Exploring/battle area

**Video or Screenshots**
![E1FBA0F8-4C94-4DAA-BCF8-D8834DD6F2FB](https://user-images.githubusercontent.com/103075468/161851202-83d4bb60-8eed-42cb-9db3-7ab940c5392c.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by squidee100** [comment] 2022-04-05 21:50
Duplicate of #187
Check other issues before making your own.

**Closed** 2022-04-05 21:58 UTC
