### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by luciolle24** [voidpet/bugs#249] opened 2022-04-05 19:01 UTC
**Describe the bug**
Tried to navigate around the map to go on the new quest and was greated with a blank screen asking me to screenshot it and make an issue here

**Expected behavior**
I expected to go to the next area

**Video or Screenshots**
![Screenshot_20220405-205347_Ecosia](https://user-images.githubusercontent.com/74781751/161829264-287baa81-6c37-4eb8-992c-72d998c9c8e5.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android 11
 - Browser Ecosia
 - Version 4.4.1

**Comment by squidee100** [comment] 2022-04-05 21:45
Duplicate of #187

**Closed** 2022-04-06 17:42 UTC
