### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by LavenderWolf65** [voidpet/bugs#259] opened 2022-04-05 20:32 UTC
Was going through and this popped up when I went out the field
![Screenshot_20220405-114850](https://user-images.githubusercontent.com/103073509/161844001-ae4527ff-76cb-4239-b29b-e7381d94e963.png)

**Comment by squidee100** [comment] 2022-04-05 21:45
Duplicate of #187

**Closed** 2022-04-06 17:42 UTC
