### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by yureda** [voidpet/bugs#260] opened 2022-04-05 20:54 UTC
Hello i went on this when i moved in the game
I was on google chrome on my samsung
Thank you
![Screenshot_20220405-224832_Chrome](https://user-images.githubusercontent.com/103074363/161847326-cf699546-67c9-47dd-9c5f-3c097479fb36.jpg)

**Comment by squidee100** [comment] 2022-04-05 21:45
Duplicate of #187

**Closed** 2022-04-06 17:42 UTC
