### ISSUE TITLE
Impossible state 

### ISSUE THREAD

**Issue by ValorPrince** [voidpet/bugs#261] opened 2022-04-05 21:18 UTC
![Screenshot (1)](https://user-images.githubusercontent.com/103074999/161850377-8106df09-30c3-4e51-839a-dbaaadc06245.png)

account name is Valor

**Comment by squidee100** [comment] 2022-04-05 21:50
Duplicate of #187
Check other issues before making your own.

**Closed** 2022-04-06 17:42 UTC
